CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE accounts(
    id UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE habits(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    account_id UUID REFERENCES accounts(id)
);